name: Android APK Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools python3-pip python3-dev build-essential unzip openjdk-8-jdk wget git libssl-dev libffi-dev

      - name: Install buildozer
        run: |
          pip3 install --user buildozer
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install Cython
        run: pip3 install cython

      # Подготовить .buildozer и SDK
      - name: Prepare Android SDK
        run: buildozer android clean || true

      # Принимаем все лицензии и сразу ставим необходимые компоненты (aidl/build-tools/platform-tools/platforms)
      - name: Accept all Android SDK licenses and install build-tools
        run: |
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;36.1.0" "platform-tools" "platforms;android-31" || true

      - name: Build the APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
