name: Android APK Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools python3-pip python3-dev build-essential unzip openjdk-8-jdk wget git libssl-dev libffi-dev
          pip3 install --upgrade pip

      - name: Install buildozer
        run: |
          pip3 install --user buildozer
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Build the APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
